#compdef c6u
# zsh completion — drop into ~/.zsh/completions/ (or add that dir to fpath)

local -a cmds
cmds=(
  'setup:first-run wizard'
  'login:verify credentials'
  'clear-password:remove stored password'
  'status:router status'
  'clients:list connected devices'
  'wan:WAN + LAN info'
  'wifi:radio states'
  'firmware:model + firmware version'
  'all:dump everything'
  'reboot:reboot router'
  'wifi-toggle:flip a radio'
  'dhcp:leases + reservations'
  'wol:Wake-on-LAN magic packet'
  'qr:WiFi QR code'
  'log:record a snapshot'
  'report:summarize recent activity'
  'metrics:Prometheus exporter'
  'web:FastAPI dashboard'
  'watch:live refresh + alerts'
  'speedtest:speedtest.net'
  'tray:system tray icon'
  'alias:manage MAC aliases'
  'vendor:MAC to vendor'
  'rdns:reverse DNS'
  'public-ip:check WAN IP'
  'firmware-check:compare to latest'
  'latency:ping every known device'
  'ping:ping one host'
  'discover:mDNS + SSDP scan'
  'presence:who is home'
  'csv:export DB tables'
  'events:recent events'
  'daemon:combined background loops'
  'mqtt:Home Assistant MQTT publisher'
  'schedule:generate task scheduler XML'
  'profiles:list multi-router profiles'
  'notify:send a push notification'
  'rules:list/test/write rules'
  'automation:list jobs / run loop'
  'watchdog:connectivity watchdog loop'
  'rotate:rotate admin password'
  'fingerprint:guess device types'
  'heatmap:per-device presence heatmap'
  'cve:CVE watcher for firmware'
  'sla:ISP SLA report'
  'extping:ping external targets'
  'telegram:Telegram bot loop'
  'discord:post alert to Discord'
  'portscan:scan public IP'
  'arpwatch:ARP spoofing detector'
  'dnscheck:DNS hijack check'
  'hibp:HaveIBeenPwned check'
  'tlswatch:router TLS cert pin watcher'
  'tui:full-screen Textual dashboard'
  'repl:interactive shell'
  'sql:ad-hoc SQL against history DB'
  'search:FTS5 event search'
  'digest:weekly HTML digest'
  'backup:create backup archive'
  'restore:restore from backup'
  'anomaly:device anomaly scanner'
)

_arguments -C '1:command:->cmd' '*::arg:->args'
case $state in
  cmd) _describe 'c6u command' cmds ;;
esac
